<?php

namespace SurveyBundle\Entity;

/**
 * FreeTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FreeTextRepository extends \Doctrine\ORM\EntityRepository
{
}
