<?php

namespace SurveyBundle\Entity;

/**
 * TemplateQRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateQRepository extends \Doctrine\ORM\EntityRepository
{
}
