security:
    encoders:
        UserBundle\Entity\User: plaintext

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        custom_provider:
            entity:
                class: UserBundle:User

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            remember_me:
                key: %secret%
                lifetime: 31536000
                path: /
                domain: ~

            form_login:
                login_path: /login
                check_path: /login-check
                username_parameter: logIn[username]
                password_parameter: logIn[password]
                use_referer: true

            logout:
                path: /logout
                invalidate_session: true
                target: /